core/urls.py
from django.urls import path
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

medicinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from contact_us.views import contact_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('carts.urls')),
    path('contact/', contact_page, name='contact-us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (
    UserLoginView, UserLogoutView, RegisterView, guest_register_view,
    ProfileView
)

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

orders/models.py
import math
from django.db import models
from carts.models import Cart
from django.db.models.signals import pre_save, post_save
from .utils import unique_order_id_generator
from addresses.models import Address

from billing.models import BillingProfile

ORDER_STATUS_CHOICES = (
    ('created', 'Created'),
    ('paid', 'Paid'),
    ('shipped', 'Shipped'),
    ('refunded', 'Refunded'),
)


class OrderManager(models.Manager):
    def new_or_get(self, billing_profile, cart_obj):
        created = False
        qs = self.get_queryset().filter(billing_profile=billing_profile, cart=cart_obj, active=True, status='created')
        if qs.count() == 1:
            obj = qs.first()
        else:
            obj = self.model.objects.create(
                billing_profile=billing_profile,
                cart=cart_obj)
            created = True
        return obj, created


class Order(models.Model):
    billing_profile = models.ForeignKey(BillingProfile, null=True, blank=True, on_delete=models.CASCADE)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', null=True, blank=True,
                                         on_delete=models.CASCADE)
    billing_address = models.ForeignKey(Address, related_name='billing_address', null=True, blank=True,
                                        on_delete=models.CASCADE)
    order_id = models.CharField(max_length=120, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='created')
    shipping_total = models.DecimalField(default=9.99, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=100, decimal_places=2)
    active = models.BooleanField(default=True)

    objects = OrderManager()

    def update_total(self):
        cart_total = self.cart.total
        shipping_total = self.shipping_total
        new_total = math.fsum([cart_total, shipping_total])
        formatted_total = format(new_total, '.2f')
        self.total = formatted_total
        self.save()
        return new_total

    def check_done(self):
        billing_profile = self.billing_profile
        shipping_address = self.shipping_address
        billing_address = self.billing_address
        total = self.total
        if billing_profile and shipping_address and billing_address and total > 0:
            return True
        return False

    def mark_paid(self):
        if self.check_done():
            self.status = 'paid'
            self.save()
        return self.status

    def __str__(self):
        return self.order_id


def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)
    qs = Order.objects.filter(cart=instance.cart).exclude(billing_profile=instance.billing_profile)
    if qs.exists():
        qs.update(active=False)


pre_save.connect(pre_save_create_order_id, sender=Order)


def post_save_cart_total(sender, instance, created, *args, **kwargs):
    if not created:
        cart_obj = instance
        cart_total = cart_obj.total
        cart_id = cart_obj.id
        qs = Order.objects.filter(cart__id=cart_id)
        if qs.count() == 1:
            order_obj = qs.first()
            order_obj.update_total()


post_save.connect(post_save_cart_total, sender=Cart)


def post_save_order(sender, instance, created, *args, **kwargs):
    if created:
        instance.update_total()


post_save.connect(post_save_order, sender=Order)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, full_name=None, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError('User must have an email')
        if not password:
            raise ValueError('User must have a password')

        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.full_name = full_name
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, full_name=None, password=None):
        user = self.create_user(email, password=password, full_name=full_name, is_staff=True)
        return user

    def create_superuser(self, email, full_name=None, password=None):
        user = self.create_user(email, password=password, full_name=full_name, is_staff=True, is_admin=True)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    full_name = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_full_name(self):
        if self.full_name:
            return self.full_name
        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class GuestEmail(models.Model):
    email = models.EmailField(max_length=255)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'active', 'admin')

    def clean_password(self):
        return self.initial["password"]


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        # user.active = False # Email verification
        if commit:
            user.save()
        return user


class GuestForm(forms.Form):
    email = forms.EmailField()

users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from billing.models import BillingProfile
from .forms import UserRegistrationForm, GuestForm
from django.utils.http import url_has_allowed_host_and_scheme
from django.shortcuts import redirect, render
from .models import GuestEmail
from .signals import user_logged_in


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    success_message = 'You are successfully logged in'

    def dispatch(self, request, *args, **kwargs):
        try:
            del request.session['guest_email_id']
        except:
            pass
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form = super(UserLoginView, self).form_valid(form)  # Complete the Login Task First.
        request = self.request
        user = request.user  # Then get the uses
        user_logged_in.send(user.__class__, instance=user, request=request)
        # print(user)
        return form


class UserLogoutView(LogoutView):
    template_name = 'users/logout.html'
    next_page = 'home'


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'users/register.html'
    success_message = 'Registration is completed. Please Login in here'


def guest_register_view(request):
    form = GuestForm(request.POST or None)
    context = {
        'form': form,
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if form.is_valid():
        email = form.cleaned_data.get('email')
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id
        if url_has_allowed_host_and_scheme(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect('users/register.html')
    return render(request, 'users/register.html', context)


class ProfileView(TemplateView):
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        user = self.request.user
        billing_profiles = BillingProfile.objects.filter(user=user)
        context = {
            "billing_profiles": billing_profiles,
        }
        return context

templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block contain %}
    <div class="container">
        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Your username or password didn't match. Please try again.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="control-label">Username</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password" class="control-label">Password</label>
                {{ form.password }}
            </div>
            <br>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Login" />
                <input type="hidden" name="next" value="{{ next }}">
                <a href="#" class="btn btn-link">Reset password</a>
            </div>
        </form>
    </div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block contain %}
    <div class="container text-center mt-2">
        <h1>Profile</h1>
        <p>{{ user.email }}</p>
        <p>{{ user.get_full_name }}</p>
        <h1>Addresses:</h1>
        <ul>
            {% for billing_profile in billing_profiles %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Address Line 1</th>
                        <th scope="col">Address Line 2</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col">Postal Code</th>
                        <th scope="col">Country</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for address in billing_profile.address_set.all %}
                        <tr>
                            <th scope="row">{{ address.id }}</th>
                            <td>{{ address.address_line_1 }}</td>
                            <td>{{ address.address_line_2 }}</td>
                            <td>{{ address.city }}</td>
                            <td>{{ address.state }}</td>
                            <td>{{ address.postal_code }}</td>
                            <td>{{ address.country }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endfor %}
        </ul>
        <h1>Orders:</h1>
        <ul>
            {% for billing_profile in billing_profiles %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Shipping Cost</th>
                        <th scope="col">Total</th>
                        <th scope="col">Shipping Address</th>
                        <th scope="col">Billing Address</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in billing_profile.order_set.all %}
                        <tr>
                            <th scope="row">{{ order.order_id }}</th>
                            <td>
                                {% if order.status == 'created' %}
                                    <span class="badge badge-primary">{{ order.status }}</span>
                                {% elif order.status == 'paid' %}
                                    <span class="badge badge-success">{{ order.status }}</span>
                                {% elif order.status == 'shipped' %}
                                    <span class="badge badge-info">{{ order.status }}</span>
                                {% elif order.status == 'refunded' %}
                                    <span class="badge badge-danger">{{ order.status }}</span>
                                {% endif %}
                            </td>
                            <td>{{ order.shipping_total }}</td>
                            <td>{{ order.total }}</td>
                            <td>{{ order.shipping_address.get_address }}</td>
                            <td>{{ order.billing_address.get_address }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block contain %}
    <div class="container">
         {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ field.errors|striptags }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="control-label">Full name</label>
                {{ form.full_name }}
            </div>
            <div class="form-group">
                <label for="username" class="control-label">Email</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="password1" class="control-label">Password</label>
                {{ form.password1 }}
            </div>
             <div class="form-group">
                <label for="password2" class="control-label">Confirm Password</label>
                {{ form.password2 }}
            </div>
            <br>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Signup" />
                <a href="{% url 'login' %}" class="btn btn-link">Login</a>
            </div>
        </form>
    </div>

{% endblock %}